org: ncatranis
app: demo-api-on-aws
service: demo-api-on-aws

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 128
plugins:
 - serverless-wsgi
 - serverless-python-requirements
custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   events:
     - http: ANY /
     - http: ANY /{proxy+}